from django.db import models

from apps.comun.consts import CRUDOperatorsEnum
from apps.comun.models import AbstractModel
from apps.facturas import consts as facturas_consts


class Factura(AbstractModel):
    """Store invoice header information.

    This model represents the invoice header for a sale, including the customer
    and total amount. The `codigo_factura` value is unique and generated by the
    system.

    Attributes:
        codigo_factura (str): Unique invoice code.
        fecha (date): Creation date for the invoice.
        cliente (str): Customer name.
        total (Decimal | None): Total amount for the invoice.
    """

    codigo_factura = models.CharField(
        max_length=8,
        unique=True,
        editable=False,
        verbose_name=facturas_consts.CODIGO_FACTURA_LABEL,
    )
    fecha = models.DateField(auto_now_add=True, verbose_name=facturas_consts.FECHA_LABEL)
    cliente = models.CharField(max_length=100, verbose_name=facturas_consts.CLIENTE_LABEL)
    total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name=facturas_consts.TOTAL_LABEL,
    )

    class Meta:
        db_table = "facturas"
        verbose_name = facturas_consts.FACTURA_VERBOSE_NAME
        verbose_name_plural = facturas_consts.FACTURA_VERBOSE_NAME_PLURAL
        ordering = ["-id"]

    def __str__(self):
        """Return the string representation of the invoice.

        Returns:
            str: Human-readable identifier for the invoice.
        """
        return facturas_consts.FACTURA_DISPLAY.format(code=self.codigo_factura)

    class Config:
        crud_operations = [
            CRUDOperatorsEnum.INDEX,
            CRUDOperatorsEnum.CREATE,
            CRUDOperatorsEnum.READ,
            CRUDOperatorsEnum.UPDATE,
            CRUDOperatorsEnum.DELETE,
        ]


class DetalleFactura(AbstractModel):
    """Store an invoice line item.

    This model represents a product line that belongs to a specific invoice.
    The `codigo_detalle` value is unique and generated by the system.

    Attributes:
        factura (Factura): Parent invoice reference.
        producto (str): Product name for the line item.
        cantidad (int): Quantity of the product.
        precio_unitario (Decimal): Unit price at the time of sale.
        subtotal (Decimal): Calculated subtotal for the line item.
        codigo_detalle (str): Unique line item code.
    """

    factura = models.ForeignKey(
        Factura,
        on_delete=models.CASCADE,
        related_name="detalles",
        verbose_name=facturas_consts.FACTURA_LABEL,
    )
    producto = models.CharField(max_length=200, verbose_name=facturas_consts.PRODUCTO_LABEL)
    cantidad = models.PositiveIntegerField(verbose_name=facturas_consts.CANTIDAD_LABEL)
    precio_unitario = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name=facturas_consts.PRECIO_UNITARIO_LABEL,
    )
    subtotal = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        editable=False,
        verbose_name=facturas_consts.SUBTOTAL_LABEL,
    )
    codigo_detalle = models.CharField(
        max_length=255,
        unique=True,
        editable=False,
        verbose_name=facturas_consts.CODIGO_DETALLE_LABEL,
    )

    class Meta:
        db_table = "detalle_factura"
        verbose_name = facturas_consts.DETALLE_FACTURA_VERBOSE_NAME
        verbose_name_plural = facturas_consts.DETALLE_FACTURA_VERBOSE_NAME_PLURAL

    def __str__(self):
        """Return the string representation of the invoice detail.

        Returns:
            str: Human-readable identifier for the detail.
        """
        return facturas_consts.DETALLE_FACTURA_DISPLAY.format(code=self.codigo_detalle)
