
services:
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    ports:
      - ${GOTENBERG_PORT}:3000
    environment:
      API_ENABLE_BASIC_AUTH: ${GOTENBERG_API_ENABLE_BASIC_AUTH}
      GOTENBERG_API_BASIC_AUTH_USERNAME: ${GOTENBERG_API_BASIC_AUTH_USERNAME}
      GOTENBERG_API_BASIC_AUTH_PASSWORD: ${GOTENBERG_API_BASIC_AUTH_PASSWORD}
