from typing import Callable, Dict, List, Optional, Set, Type, Union

from asgiref.sync import sync_to_async
from django.contrib.auth.models import Permission
from django_filters import FilterSet
from ninja_extra import (
    ModelControllerBase as NinjaExtraModelControllerBase,
)
from ninja_extra.controllers.model.schemas import ModelPagination
from ninja_extra.exceptions import PermissionDenied
from ninja_extra.permissions import AsyncBasePermission, BasePermission
from pydantic import BaseModel as PydanticModel, Field

from .service import GenericModelService


class BaseApiController(NinjaExtraModelControllerBase):
    """Base API Controller for handling CRUD operations.

    This class provides a foundation for creating controllers that automatically generate CRUD operations.
    Developers can customize CRUD behavior by overriding the `service` attribute.

    Attributes:
        model (Type[models.Model] | None):
            The Django model associated with this controller.

        allowed_routes (List[str]):
            A list of allowed CRUD operations for the controller.
            Must be one or more of the following: ["create", "find_one", "update", "patch", "delete", "list"].

        async_routes (bool):
            Whether the routes should be asynchronous. Defaults to False.

        create_schema (Type[PydanticModel] | None):
            Pydantic schema used for the autogenerated create endpoint.

        retrieve_schema (Type[PydanticModel] | None):
            Pydantic schema used for retrieving objects.

        update_schema (Type[PydanticModel] | None):
            Pydantic schema used for the autogenerated update endpoint.

        patch_schema (Type[PydanticModel] | None):
            Pydantic schema used for the autogenerated patch endpoint.

        create_response_schema (Type[PydanticModel] | None):
            Pydantic response schema for the autogenerated create endpoint.

        update_response_schema (Type[PydanticModel] | None):
            Pydantic response schema for the autogenerated update endpoint.

        patch_response_schema (Type[PydanticModel] | None):
            Pydantic response schema for the autogenerated patch endpoint.

        delete_response_schema (Type[PydanticModel] | None):
            Pydantic response schema for the autogenerated delete endpoint.

        create_route_info (Dict):
            Additional metadata for the create endpoint. Can include path, summary, authentication method,
            description, and permissions (Django permissions like "movies.add_movie").

        find_one_route_info (Dict):
            Additional metadata for the find_one endpoint. Can include path, summary, authentication method,
            description, and permissions.

        update_route_info (Dict):
            Additional metadata for the update endpoint. Can include path, summary, authentication method,
            description, and permissions.

        patch_route_info (Dict):
            Additional metadata for the patch endpoint. Can include path, summary, authentication method,
            description, and permissions.

        list_route_info (Dict):
            Additional metadata for the list endpoint. Can include path, summary, authentication method,
            description, and permissions.

        delete_route_info (Dict):
            Additional metadata for the delete endpoint. Can include path, summary, authentication method,
            description, and permissions.

        exclude_fields (Set[str] | None):
            Fields to exclude from the schema.

        include (Union[str, List[str]]):
            Fields to include in the schema. Defaults to "__all__".

        optional (Optional[Union[str, Set[str]]]):
            Fields that should be optional in the schema.

        write_only_fields (Optional[List[str]]):
            Fields that should only be used for writing and not exposed in responses.

        read_only_fields (Optional[List[str]]):
            Fields that should only be used for reading and not modifiable by clients.

        pre_save (Optional[Callable]):
            A callable function executed before saving an object.

        post_save (Optional[Callable]):
            A callable function executed after saving an object.

        filterset_class (Optional[Type[FilterSet]]):
            A filter set class for filtering querysets. Must inherit from `django_filters.FilterSet`.

        pagination (Type[ModelPagination]):
            Pagination configuration for list endpoints.
            For more details, refer to the documentation: https://eadwincode.github.io/django-ninja-extra/api_controller/model_controller/02_model_configuration/#pagination-configuration
    """

    # Configuration for ModelController
    model = None
    allowed_routes: List[str] = [
        "create",
        "find_one",
        "update",
        "patch",
        "delete",
        "list",
    ]
    async_routes: bool = False
    create_schema: Type[PydanticModel] | None = None
    retrieve_schema: Type[PydanticModel] | None = None
    update_schema: Type[PydanticModel] | None = None
    patch_schema: Type[PydanticModel] | None = None

    create_response_schema: Type[PydanticModel] | None = None
    update_response_schema: Type[PydanticModel] | None = None
    patch_response_schema: Type[PydanticModel] | None = None
    delete_response_schema: Type[PydanticModel] | None = None

    create_route_info: Dict = {}  # extra @post() information
    find_one_route_info: Dict = {}  # extra @get('/{id}') information
    update_route_info: Dict = {}  # extra @put() information
    patch_route_info: Dict = {}  # extra @patch() information
    list_route_info: Dict = {}  # extra @get('/') information
    delete_route_info: Dict = {}  # extra @delete() information

    # Configuration for Schema config
    exclude_fields: Set[str] | None = None
    include: Union[str, List[str]] = Field(default="__all__")
    optional: Optional[Union[str, Set[str]]] = Field(default=None)
    write_only_fields: Optional[Union[List[str]]] = Field(default=None)
    read_only_fields: Optional[List[str]] = Field(default=None)

    pre_save: Optional[Callable] = None
    post_save: Optional[Callable] = None

    filterset_class: Optional[Type[FilterSet]] = None
    pagination: Type[ModelPagination] = None
    service_type = GenericModelService

    def check_permissions(self) -> None:
        """Check if the request should be permitted.

        Raises an appropriate exception if the request is not permitted.
        """
        for permission in self._get_permissions():
            if isinstance(permission, str) or isinstance(permission, Permission):
                self.handle_django_permissions(permission=permission)
                continue
            if (
                self.context
                and self.context.request
                and not permission.has_permission(request=self.context.request, controller=self)
            ):
                self.permission_denied(permission)

    async def async_check_permissions(self) -> None:
        """Asynchronous version of check_permissions.

        Check if the request should be permitted, using async permission checks when available.
        Raises an appropriate exception if the request is not permitted.
        """
        if not self.context or not self.context.request:  # pragma: no cover
            return

        for permission in self._get_permissions():
            has_permission = False
            if isinstance(permission, str) or isinstance(permission, Permission):
                await self.async_handle_django_permissions(permission=permission)
                continue
            elif isinstance(permission, AsyncBasePermission):
                has_permission = await permission.has_permission_async(request=self.context.request, controller=self)
            else:
                has_permission = await sync_to_async(permission.has_permission)(
                    request=self.context.request, controller=self
                )

            if not has_permission:
                self.permission_denied(permission)

    def handle_django_permissions(self, permission: Permission | str):  # noqa
        if self.context and self.context.request:
            context_user = self.context.request.user
            if isinstance(permission, str):
                if not context_user.has_perm(permission):
                    self.permission_denied(permission=permission)
            else:
                permission_codename = f"{permission.content_type.app_label}.{permission.codename}"
                if not context_user.has_perm(permission_codename):
                    self.permission_denied(permission=permission)

    async def async_handle_django_permissions(self, permission: Permission | str):  # noqa
        if self.context and self.context.request:
            context_user = self.context.request.user
            if isinstance(permission, str):
                if not await context_user.ahas_perm(permission):
                    self.permission_denied(permission=permission)
            else:
                permission_codename = f"{permission.content_type.app_label}.{permission.codename}"
                if not await context_user.ahas_perm(permission_codename):
                    self.permission_denied(permission=permission)

    def check_object_permissions(self, obj):
        """Check if the request should be permitted for a given object.

        Raises an appropriate exception if the request is not permitted.
        """
        for permission in self._get_permissions():
            if isinstance(permission, str) or isinstance(permission, Permission):
                continue
            if (
                self.context
                and self.context.request
                and not permission.has_object_permission(request=self.context.request, controller=self, obj=obj)
            ):
                self.permission_denied(permission)

    async def async_check_object_permissions(self, obj):
        """Asynchronous version of check_object_permissions.

        Check if the request should be permitted for a given object, using async permission checks when available.
        Raises an appropriate exception if the request is not permitted.
        """
        if not self.context or not self.context.request:  # pragma: no cover
            return

        for permission in self._get_permissions():
            has_permission = False
            if isinstance(permission, str) or isinstance(permission, Permission):
                continue
            elif isinstance(permission, AsyncBasePermission):
                has_permission = await permission.has_object_permission_async(
                    request=self.context.request, controller=self, obj=obj
                )
            else:
                has_permission = await sync_to_async(permission.has_object_permission)(
                    request=self.context.request, controller=self, obj=obj
                )

            if not has_permission:
                self.permission_denied(permission)

    @classmethod
    def permission_denied(cls, permission: Union[BasePermission, AsyncBasePermission, Permission, str]) -> None:  # noqa
        if isinstance(permission, str) or isinstance(permission, Permission):
            raise PermissionDenied()
        message = getattr(permission, "message", None)
        raise PermissionDenied(message)
