"""Shared constants for the HU documentation script.
"""
VIEWS = "views"
VIEW = "view"
RAW = "raw"
ENTRY = "entry"
FILE = "file"
LINE = "line"
LINEO = "lineo"
META = "Meta"
HUS = "HUs"
ID = "id"
NO_DESC = "No description available"
DESCRIPTION = "description"
